passed
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
Run options: 

# Running tests:

.............F.E......merge(:edited, :testing, :interactive)
confirm_commit(:interactive something_to_commit?=false
.$ ruby  script/work_flow.rb --merge-down
@errors="/usr/lib/ruby/vendor_ruby/minitest/unit.rb:180:in `assert': unexpected stash apply failself=$ git stash apply --quiet (MiniTest::Assertion)\n.\n<0> expected but was\n<1>.\n\tfrom /usr/lib/ruby/1.9.1/test/unit/assertions.rb:38:in `assert'\n\tfrom /usr/lib/ruby/1.9.1/test/unit/assertions.rb:187:in `assert_equal'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/shell_command.rb:285:in `assert_post_conditions'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/repository.rb:272:in `safely_visit_branch'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:316:in `block in merge_down'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:315:in `each'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:315:in `merge_down'\n\tfrom script/work_flow.rb:114:in `block in <main>'\n\tfrom script/work_flow.rb:97:in `each'\n\tfrom script/work_flow.rb:97:in `<main>'\n"
$ echo "Hello World"
Hello World
$ echo "1 2;3 4"
1 2;3 4
$ $?=1
@errors="sh: 1: 0=1: not found\n"
$ ls happyHappyFailFail.junk
@errors="ls: cannot access happyHappyFailFail.junk: No such file or directory\n"
$ file -b script/work_flow.rb
Ruby script, ASCII text executable
$ file -b --mime script/work_flow.rb
text/x-ruby; charset=us-ascii
$ file -b script/work_flow.rb
Ruby script, ASCII text executable
$ file -b --mime script/work_flow.rb
text/x-ruby; charset=us-ascii
work_flow --<command> <file>
$ git stash save --include-untracked
@errors="Ignoring path test/data_sources/repository2015-03-31 07:42:37.001/\nIgnoring path test/data_sources/repository2015-03-31 07:43:13.982/\nIgnoring path test/data_sources/repository2015-03-31 07:45:32.841/\n"
Saved working directory and index state WIP on master: 8c3693c fixup! repository
HEAD is now at 8c3693c fixup! repository
$ git status --porcelain --untracked-files=no|grep "UU "
$ git checkout passed
@errors="Switched to branch 'passed'\n"
Your branch is ahead of 'origin/passed' by 17 commits.
merge(passed), edited)
merge(:passed, :edited, :interactive)
$ git merge --no-commit edited
Already up-to-date.
confirm_commit(:interactive something_to_commit?=false
No merge conflict
confirm_commit(:interactive something_to_commit?=false
$ git checkout master
@errors="fatal: Unable to create '/home/greg/Desktop/src/Open-Table-Explorer/.git/index.lock': File exists.\n\nIf no other git process is currently running, this probably means a\ngit process crashed in this repository earlier. Make sure no other git\nprocess is running and remove the file manually to continue.\n"
$ git stash apply --quiet
F.F.......

Finished tests in 7.881729s, 4.1869 tests/s, 699.9734 assertions/s.

  1) Failure:
test_deserving_branch?(WorkFlowTest) [test/unit/work_flow_test.rb:219]:
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
Run options: 

# Running tests:

E.

Finished tests in 0.000822s, 2432.9480 tests/s, 0.0000 assertions/s.

  1) Error:
test_fail(SingleFailTest):
RuntimeError: 
    test/data_sources/repository//single_test_fail.rb:6:in `test_fail'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:1058:in `run'
    /usr/lib/ruby/1.9.1/test/unit/testcase.rb:17:in `run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:823:in `block in _run_suite'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:815:in `map'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:815:in `_run_suite'
    /usr/lib/ruby/1.9.1/test/unit.rb:565:in `block in _run_suites'
    /usr/lib/ruby/1.9.1/test/unit.rb:563:in `each'
    /usr/lib/ruby/1.9.1/test/unit.rb:563:in `_run_suites'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:775:in `_run_anything'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:964:in `run_tests'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:951:in `block in _run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:950:in `each'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:950:in `_run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:939:in `run'
    /usr/lib/ruby/1.9.1/test/unit.rb:21:in `run'
    /usr/lib/ruby/1.9.1/test/unit.rb:326:in `block (2 levels) in autorun'
    /usr/lib/ruby/1.9.1/test/unit.rb:27:in `run_once'
    /usr/lib/ruby/1.9.1/test/unit.rb:325:in `block in autorun'

2 tests, 0 assertions, 0 failures, 1 errors, 0 skips
.
<1> expected but was
<0>.

  2) Error:
test_differences?(WorkFlowTest):
RuntimeError: test/long_test/repository_test.rb does not exist.
    /home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:109:in `diff_command?'
    /home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:123:in `working_different_from?'
    test/unit/work_flow_test.rb:125:in `test_differences?'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:1058:in `run'
    /usr/lib/ruby/1.9.1/test/unit/testcase.rb:17:in `run'
    /usr/lib/ruby/vendor_ruby/active_support/testing/setup_and_teardown.rb:36:in `block in run'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:403:in `_run__824161180899716831__setup__3121040037703865708__callbacks'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:405:in `__run_callback'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:385:in `_run_setup_callbacks'
    /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
    /usr/lib/ruby/vendor_ruby/active_support/testing/setup_and_teardown.rb:35:in `run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:823:in `block in _run_suite'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:815:in `map'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:815:in `_run_suite'
    /usr/lib/ruby/1.9.1/test/unit.rb:565:in `block in _run_suites'
    /usr/lib/ruby/1.9.1/test/unit.rb:563:in `each'
    /usr/lib/ruby/1.9.1/test/unit.rb:563:in `_run_suites'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:775:in `_run_anything'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:964:in `run_tests'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:951:in `block in _run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:950:in `each'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:950:in `_run'
    /usr/lib/ruby/vendor_ruby/minitest/unit.rb:939:in `run'
    /usr/lib/ruby/1.9.1/test/unit.rb:21:in `run'
    /usr/lib/ruby/1.9.1/test/unit.rb:326:in `block (2 levels) in autorun'
    /usr/lib/ruby/1.9.1/test/unit.rb:27:in `run_once'
    /usr/lib/ruby/1.9.1/test/unit.rb:325:in `block in autorun'

  3) Failure:
test_merge_command(WorkFlowTest) [test/unit/work_flow_test.rb:251]:
self=$ ruby  script/work_flow.rb --merge-down
@errors="/usr/lib/ruby/vendor_ruby/minitest/unit.rb:180:in `assert': unexpected stash apply failself=$ git stash apply --quiet (MiniTest::Assertion)\n.\n<0> expected but was\n<1>.\n\tfrom /usr/lib/ruby/1.9.1/test/unit/assertions.rb:38:in `assert'\n\tfrom /usr/lib/ruby/1.9.1/test/unit/assertions.rb:187:in `assert_equal'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/shell_command.rb:285:in `assert_post_conditions'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/repository.rb:272:in `safely_visit_branch'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:316:in `block in merge_down'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:315:in `each'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:315:in `merge_down'\n\tfrom script/work_flow.rb:114:in `block in <main>'\n\tfrom script/work_flow.rb:97:in `each'\n\tfrom script/work_flow.rb:97:in `<main>'\n"
$ echo "Hello World"
Hello World
$ echo "1 2;3 4"
1 2;3 4
$ $?=1
@errors="sh: 1: 0=1: not found\n"
$ ls happyHappyFailFail.junk
@errors="ls: cannot access happyHappyFailFail.junk: No such file or directory\n"
$ file -b script/work_flow.rb
Ruby script, ASCII text executable
$ file -b --mime script/work_flow.rb
text/x-ruby; charset=us-ascii
$ file -b script/work_flow.rb
Ruby script, ASCII text executable
$ file -b --mime script/work_flow.rb
text/x-ruby; charset=us-ascii
work_flow --<command> <file>
$ git stash save --include-untracked
@errors="Ignoring path test/data_sources/repository2015-03-31 07:42:37.001/\nIgnoring path test/data_sources/repository2015-03-31 07:43:13.982/\nIgnoring path test/data_sources/repository2015-03-31 07:45:32.841/\n"
Saved working directory and index state WIP on master: 8c3693c fixup! repository
HEAD is now at 8c3693c fixup! repository
$ git status --porcelain --untracked-files=no|grep "UU "
$ git checkout passed
@errors="Switched to branch 'passed'\n"
Your branch is ahead of 'origin/passed' by 17 commits.
merge(passed), edited)
merge(:passed, :edited, :interactive)
$ git merge --no-commit edited
Already up-to-date.
confirm_commit(:interactive something_to_commit?=false
No merge conflict
confirm_commit(:interactive something_to_commit?=false
$ git checkout master
@errors="fatal: Unable to create '/home/greg/Desktop/src/Open-Table-Explorer/.git/index.lock': File exists.\n\nIf no other git process is currently running, this probably means a\ngit process crashed in this repository earlier. Make sure no other git\nprocess is running and remove the file manually to continue.\n"
$ git stash apply --quiet
expected errors to be empty\n
"/usr/lib/ruby/vendor_ruby/minitest/unit.rb:180:in `assert': unexpected stash apply failself=$ git stash apply --quiet (MiniTest::Assertion)\n.\n<0> expected but was\n<1>.\n\tfrom /usr/lib/ruby/1.9.1/test/unit/assertions.rb:38:in `assert'\n\tfrom /usr/lib/ruby/1.9.1/test/unit/assertions.rb:187:in `assert_equal'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/shell_command.rb:285:in `assert_post_conditions'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/repository.rb:272:in `safely_visit_branch'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:316:in `block in merge_down'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:315:in `each'\n\tfrom /home/greg/Desktop/src/Open-Table-Explorer/app/models/work_flow.rb:315:in `merge_down'\n\tfrom script/work_flow.rb:114:in `block in <main>'\n\tfrom script/work_flow.rb:97:in `each'\n\tfrom script/work_flow.rb:97:in `<main>'\n" is not empty.

  4) Failure:
test_minimal_comparison(WorkFlowTest) [test/unit/work_flow_test.rb:209]:
<" -t app/models/work_flow.rb app/models/minimal2.rb -t test/unit/work_flow_test.rb test/unit/minimal2_test.rb -t script/work_flow.rb script/minimal2.rb -t test/integration/work_flow_test.rb test/integration/minimal2_test.rb -t test/long_test/work_flow_test.rb test/long_test/minimal2_test.rb -t test/assertions/work_flow_assertions.rb test/assertions/minimal2_assertions.rb -t test/unit/work_flow_assertions_test.rb test/unit/minimal2_assertions_test.rb -t log/library/work_flow.log log/library/minimal2.log -t log/assertions/work_flow.log log/assertions/minimal2.log -t log/integration/work_flow.log log/integration/minimal2.log -t log/long/work_flow.log log/long/minimal2.log -t test/data_sources/work_flow test/data_sources/minimal2"> expected but was
<" -t app/models/work_flow.rb app/models/minimal2.rb -t test/unit/work_flow_test.rb test/unit/minimal2_test.rb">.

33 tests, 5517 assertions, 3 failures, 1 errors, 0 skips
